#!/usr/bin/env python3
"""Rebuild the late-cancellation policy PDF on the Desert coral & sage brand guide.

The liability waiver used to be built here too. It now has its own builder,
docs/source/build-waiver.py, because it carries a version and an effective date
that must not be silently regenerated by an unrelated run.

Guide, section 07: "Client documents — One-ink mark, white paper, Archivo 11pt
body, coral for headings only."
"""
import base64, os, shutil, subprocess, tempfile

SC = tempfile.mkdtemp(prefix='abf-pdf-')
FONTS = '/Users/michaeldevore/AI_projects/elliebfit-site/assets/fonts'
OUT = SC + '/pdfout2'
os.makedirs(OUT, exist_ok=True)
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'


def face(family, weight, filename):
    b64 = base64.b64encode(open(os.path.join(FONTS, filename), 'rb').read()).decode()
    return (f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weight};"
            f"font-display:block;src:url(data:font/woff2;base64,{b64}) format('woff2');}}")


FACES = ''.join([
    face('Barlow Condensed', 600, 'barlow-condensed-600.woff2'),
    face('Barlow Condensed', 700, 'barlow-condensed-700.woff2'),
    face('Archivo', 400, 'archivo-400.woff2'),
    face('Archivo', 500, 'archivo-400.woff2'),
    face('Archivo', 600, 'archivo-400.woff2'),
])

# One-ink Ascent mark: a single ink at the brand's three tints.
MARK = ('<svg class="mark" viewBox="0 0 100 100" width="34" height="34" fill="none">'
        '<polygon points="50,8 92,50 76,50 50,24 24,50 8,50" fill="currentColor"></polygon>'
        '<polygon points="50,30 92,72 76,72 50,46 24,72 8,72" fill="currentColor" opacity="0.62"></polygon>'
        '<polygon points="50,52 92,94 76,94 50,68 24,94 8,94" fill="currentColor" opacity="0.3"></polygon>'
        '</svg>')

CSS = """
:root{
  --coral:#E4795A; --coral-deep:#D46B4D; --sage-deep:#2E4A42; --ink:#20342E;
  --peach:#F7DCC9; --sage-tint:#CFE2D8; --muted:#6B8078;
}
@page{ size: Letter; margin: 0.5in 0.68in 0.55in; }
*{ margin:0; padding:0; box-sizing:border-box; }
html,body{ background:#fff; }            /* white paper */
body{
  font-family:'Archivo','Helvetica Neue',Helvetica,Arial,sans-serif;
  font-size:11pt; line-height:1.5; color:var(--ink);
  -webkit-font-smoothing:antialiased;
}

/* ---- letterhead: one-ink mark ---- */
.letterhead{ display:flex; align-items:flex-end; justify-content:space-between;
  gap:20px; padding-bottom:10px; }
.lockup{ display:flex; align-items:center; gap:10px; color:var(--ink); }
.lockup .mark{ flex:none; }
.wm1{ font-family:'Barlow Condensed',Arial Narrow,sans-serif; font-weight:700;
  font-size:17pt; line-height:.95; letter-spacing:.02em; text-transform:uppercase; }
.wm2{ font-size:6pt; letter-spacing:.34em; text-transform:uppercase;
  color:var(--muted); margin-top:3px; }
.contact{ text-align:right; font-size:7.5pt; line-height:1.5; color:var(--muted); }
.rule{ height:1px; background:var(--peach); margin-bottom:16px; }

/* ---- headings: coral only ---- */
h1{ font-family:'Barlow Condensed',Arial Narrow,sans-serif; font-weight:700;
  font-size:24pt; line-height:.92; letter-spacing:.02em; text-transform:uppercase;
  color:var(--coral); margin-bottom:3px; }
.subtitle{ font-size:8pt; letter-spacing:.18em; text-transform:uppercase;
  font-weight:600; color:var(--muted); margin-bottom:15px; }
h2{ font-family:'Barlow Condensed',Arial Narrow,sans-serif; font-weight:700;
  font-size:13pt; line-height:1; letter-spacing:.02em; text-transform:uppercase;
  color:var(--coral); margin:13px 0 5px; break-after:avoid; }

/* ---- body ---- */
p{ margin-bottom:7px; }
strong{ font-weight:600; }
section{ break-inside:avoid; }

.initial{ margin-top:6px; display:flex; align-items:center; gap:9px; }
.initial .box{ width:56px; height:19px; border:1px solid var(--sage-tint); border-radius:4px; }
.initial .lbl{ font-size:7pt; letter-spacing:.18em; text-transform:uppercase;
  font-weight:600; color:var(--muted); }

/* ---- signatures ---- */
.sigblock{ margin-top:16px; break-inside:avoid; }
.sigrow{ display:flex; gap:18px; margin-top:18px; }
.sig{ flex:1; } .sig.date{ flex:0 0 128px; }
.sigline{ border-bottom:1px solid var(--ink); height:25px; }
.siglabel{ font-size:7pt; letter-spacing:.18em; text-transform:uppercase;
  font-weight:600; color:var(--muted); margin-top:4px; }
.minor{ margin-top:15px; border-left:3px solid var(--sage-tint);
  padding:2px 0 2px 11px; font-size:9pt; color:var(--ink); }

/* ---- policy ---- */
.policy p{ font-size:11.5pt; line-height:1.62; margin-bottom:13px; max-width:640px; }
.callout{ border-left:3px solid var(--coral); padding:3px 0 3px 13px;
  margin:15px 0; font-size:11.5pt; line-height:1.62; max-width:640px; }
.signoff{ margin-top:24px; font-family:'Barlow Condensed',Arial Narrow,sans-serif;
  font-weight:700; font-size:13pt; letter-spacing:.02em; text-transform:uppercase;
  color:var(--coral); }

footer{ margin-top:20px; padding-top:8px; border-top:1px solid var(--peach);
  font-size:7pt; letter-spacing:.18em; text-transform:uppercase; color:var(--muted);
  display:flex; justify-content:space-between; }
"""

CONTACT = ("<div class='contact'>Above &amp; Beyond Fitness LLC<br>Scottsdale, Arizona<br>"
           "ellen@elliebfit.com &middot; elliebfit.com</div>")


def shell(title, subtitle, body, doc_id):
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<title>{title}</title><style>{FACES}{CSS}</style></head><body>
<div class="letterhead">
  <div class="lockup">{MARK}<div><div class="wm1">Above &amp; Beyond</div>
  <div class="wm2">Fitness &middot; Scottsdale AZ</div></div></div>
  {CONTACT}
</div>
<div class="rule"></div>
<h1>{title}</h1>
<div class="subtitle">{subtitle}</div>
{body}
<footer><span>Above &amp; Beyond Fitness LLC</span><span>{doc_id}</span></footer>
</body></html>"""


def ini():
    return ('<div class="initial"><span class="lbl">Please initial</span>'
            '<span class="box"></span></div>')


AB = 'Above &amp; Beyond Fitness'
policy = """
<div class="policy">
<p>I understand that plans change. If you need to cancel or reschedule, please provide at least
24&nbsp;hours&rsquo; notice. Cancellations made with less than 24&nbsp;hours&rsquo; notice will be
charged as scheduled.</p>
<div class="callout">If Ellen has availability, you may reschedule the session before the end of
that same week and use it instead of losing it.</div>
<p>Thank you for respecting the schedule and helping keep training times available for everyone.</p>
<div class="signoff">Progress has a path.</div>
</div>
"""

for name, html in [
    ('late-cancel-policy', shell('Late Cancellation Policy',
                                 '24 hours&rsquo; notice &middot; All scheduled sessions',
                                 policy, 'Cancellation Policy')),
]:
    src = os.path.join(OUT, name + '.html')
    pdf = os.path.join(OUT, name + '.pdf')
    open(src, 'w', encoding='utf-8').write(html)
    subprocess.run([CHROME, '--headless', '--disable-gpu', '--no-sandbox',
                    '--allow-file-access-from-files', '--no-pdf-header-footer',
                    f'--print-to-pdf={pdf}', 'file://' + src],
                   check=True, capture_output=True, timeout=120)
    dest = os.path.join(os.path.dirname(__file__), '..', name + '.pdf')
    shutil.copyfile(pdf, dest)
    print(f'docs/{name}.pdf  {os.path.getsize(pdf):,} bytes')
