#!/usr/bin/env python3
"""Mirror the homepage's SEO head into the bundle template, which survives hydration.

The problem
-----------
`index.html` carries a full SEO head -- title, description, canonical, Open
Graph, Twitter card, robots, geo, and JSON-LD. None of it survived in the
browser. The bundle runtime ends with

    document.documentElement.replaceWith(doc.documentElement)

which throws away the entire original document, head included, and replaces it
with `__bundler/template`. That template's head held only charset and viewport,
so after hydration the live page had **no title element at all**, two meta tags,
zero JSON-LD, and no `lang` attribute.

A raw fetch still showed the metadata, so anything that does not run JavaScript
-- Facebook, Twitter/X, LinkedIn, Slack unfurls -- was fine. Googlebot, which
indexes the *rendered* DOM, was not; nor was the browser tab, which showed the
bare URL instead of a title, nor a screen reader trying to determine language.

The fix
-------
The template's `<helmet>` block is the part the DC runtime hoists into the head
of the swapped-in document -- it is why the favicon works. This script copies the
SEO tags out of the static head and into that helmet, between markers, so the
static head stays the single source of truth and the two cannot drift.

Run it after editing any head metadata in `index.html`. Idempotent.

Usage:
    python3 docs/source/sync-head-meta.py
"""
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
INDEX = os.path.join(ROOT, 'index.html')

START = '<!-- abf:head-meta start (generated by docs/source/sync-head-meta.py) -->'
END = '<!-- abf:head-meta end -->'

# Tags deliberately NOT mirrored:
#   charset / viewport   - the template head already declares them
#   rel="preload"        - their whole job is to run during the initial parse,
#                          before hydration; repeating them post-swap is waste
#   rel="icon" / apple-  - already hand-placed in the helmet
SKIP_META_NAMES = {'viewport'}
KEEP_LINK_RELS = {'canonical'}


def die(msg):
    sys.exit(f'error: {msg}')


def encode_for_script(obj):
    """Serialise so a literal </script> in the payload cannot close the host tag."""
    return json.dumps(obj, ensure_ascii=False).replace('</', '<\\/')


def collect(static_head):
    """Pull the SEO-relevant tags out of the static head, in document order."""
    out = []
    for m in re.finditer(r'<title>.*?</title>|<meta\b[^>]*>|<link\b[^>]*>', static_head, re.S):
        tag = m.group(0)
        if tag.startswith('<title'):
            out.append(tag)
        elif tag.startswith('<meta'):
            if re.search(r'\bcharset=', tag):
                continue
            name = re.search(r'\b(?:name|property)="([^"]+)"', tag)
            if not name or name.group(1) in SKIP_META_NAMES:
                continue
            out.append(tag)
        else:  # link
            rel = re.search(r'\brel="([^"]+)"', tag)
            if rel and rel.group(1) in KEEP_LINK_RELS:
                out.append(tag)
    return out


def main():
    s = open(INDEX, encoding='utf-8').read()

    head_end = s.find('</head>')
    if head_end == -1:
        die('no </head> in the static document')
    static_head = s[:head_end]

    tags = collect(static_head)
    if not any(t.startswith('<title') for t in tags):
        die('no <title> found in the static head -- nothing to mirror')

    # JSON-LD lives outside <head> in the static document; take it wherever it is.
    ld = re.findall(r'<script type="application/ld\+json">.*?</script>', s, re.S)

    block = '\n'.join([START] + tags + ld + [END])

    t_match = re.search(r'(<script type="__bundler/template">)(.*?)(</script>)', s, re.S)
    if not t_match:
        die('no __bundler/template block')
    template = json.loads(t_match.group(2))

    # The document that replaces ours needs its own lang, or assistive tech and
    # Google both see a page with no declared language.
    template, n = re.subn(r'<html(?![^>]*\blang=)', '<html lang="en"', template, count=1)
    if n:
        print('  added lang="en" to the template <html>')

    hm = re.search(r'(<helmet>)(.*?)(</helmet>)', template, re.S)
    if not hm:
        die('no <helmet> block in the template -- nothing hoists into the head')
    inner = hm.group(2)

    existing = re.search(re.escape(START) + r'.*?' + re.escape(END), inner, re.S)
    inner = (inner[:existing.start()] + block + inner[existing.end():]) if existing \
        else inner.rstrip() + '\n' + block + '\n'

    template = template[:hm.start(2)] + inner + template[hm.end(2):]

    s = s[:t_match.start(2)] + encode_for_script(template) + s[t_match.end(2):]
    open(INDEX, 'w', encoding='utf-8').write(s)

    print(f'  mirrored {len(tags)} head tags + {len(ld)} JSON-LD block(s) into <helmet>')


if __name__ == '__main__':
    main()
